version: '3'

services:
  django:
    container_name: mindminer_django
    restart: always
    build:
      context: ./backend/django
    volumes:
      - ./backend/django/:/app/
      - staticfiles:/app/mindminer/staticfiles
      - mediafiles:/app/mindminer/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./backend/env/main.env
    depends_on:
      - postgres

  postgres:
    container_name: mindminer_postgres
    restart: always
    image: postgres:11.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./backend/env/main.env

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/mindminer
      - /usr/src/app/node_modules

volumes:
  postgres_data:
  staticfiles:
  mediafiles:
