version: '3'

services:
  django:
    container_name: mindminer_django
    restart: always
    build:
      context: ./backend/django
    volumes:
      - ./backend/django/:/app/
      - staticfiles:/app/mindminer/staticfiles
      - mediafiles:/app/mindminer/mediafiles
    ports:
      - 8000:8000
    env_file:
      - ./backend/env/main.env
      - ./backend/env/api_keys.env
    depends_on:
      - postgres
    networks:
      - mindminer

  postgres:
    container_name: mindminer_postgres
    restart: always
    image: postgres:11.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./backend/env/main.env
    networks:
      - mindminer

  redis:
    container_name: mindminer_redis
    restart: always
    image: redis:alpine3.12
    networks:
      - mindminer

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
    ports:
      - 80:3000
    networks:
      - mindminer

volumes:
  postgres_data:
  staticfiles:
  mediafiles:

networks:
  mindminer:
    external: false
    name: mindminer
