version: '3.7'

services:
  crawlers:
    container_name: mindminer_crawlers
    build: ./scrapy
    working_dir: /code
  mongo:
    container_name: mindminer_crawlers_mongodb
    image: mongo:4.2.2
    restart: always
    volumes:
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
