{
 "title": "Mindminer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Mindminer web", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quantidades de novos assuntos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  registration_date AS \"time\",\n  count(popularity) AS \"popularity\"\nFROM subject_subject\nWHERE\n  no_data = 'yes'\nGROUP BY registration_date\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Últimas notícias",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  published_at AS \"time\",\n  title\nFROM news_news\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Novos assuntos",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  hashtag\nFROM subject_subject\nWHERE\n  no_data = 'yes'"
    }
   ]
  },
  {
   "title": "Assuntos com dados processados",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  hashtag\nFROM subject_subject\nWHERE\n  no_data = 'no'"
    }
   ]
  },
  { "title": "MindMiner Data Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total de comentários capturados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.tweet.aggregate([{\"$group\": { \"_id\":  null, \"count\": { \"$sum\": 1 }}}])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Quantidade de comentários capturados por minuto",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "target": "db.tweet.aggregate( [{\"$match\": { \"discover_date\": {\"$gte\": \"$from\", \"$lte\": \"$to\" }}}, {\"$project\": {\"name\" : \"Velocidade\", \"value\": \"$discover_date\", \"ts\" : \"$discover_date\", \"_id\" : 0}}])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Total de comentários processados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.tweet.aggregate([{\"$match\": {\"analysis_result\" : {\"$ne\": \"\"}}}, {\"$group\": { \"_id\":  null, \"count\": { \"$sum\": 1 }}}])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Total de comentários não analisados ainda",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.tweet.aggregate([{\"$match\": {\"analysis_result\" : {\"$eq\": \"\"}}}, {\"$group\": { \"_id\":  null, \"count\": { \"$sum\": 1 }}}])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Robô",
   "type": "text",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "<div style=\"text-align: center\"><h1>Versão do Treinamento</h1></div>\n\n<div style=\"text-align: center\"><img src=\"https://emojipedia-us.s3.amazonaws.com/source/skype/289/robot_1f916.png\"></div>\n\n<div style=\"text-align: center\"><h2>Treinamento na versão <b>0.01</b> 📑</h2></div>\n<div style=\"text-align: center\"><h2>Link: <b>http://mindminer.tk/releases/</b></h2></div>\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  training_date AS \"time\",\n  accuracy\nFROM about_training\nWHERE\n  $__timeFilter(training_date)\nORDER BY 1"
    }
   ]
  }
 ]
}