version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    build: .
    command: cd /usr/share/grafana/var/lib/grafana/plugins/mongodb-grafana && npm run server
    ports:
      - "3000:3000"
    networks:
      - loki
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
