# Generated by Django 3.2.3 on 2021-08-25 04:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('newspaper', models.CharField(max_length=200, verbose_name='Newspaper')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('source_url', models.URLField(verbose_name='Source URL')),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('published_at', models.DateTimeField(verbose_name='Published Date')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['published_at'],
            },
        ),
    ]
