# Generated by Django 3.2.3 on 2021-08-26 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
