# Generated by Django 3.2.3 on 2021-05-24 02:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hashtag', models.CharField(max_length=200, verbose_name='Hashtag')),
                ('publication_date', models.DateTimeField(verbose_name='Publication Date')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('popularity', models.IntegerField(verbose_name='Popularity')),
                ('interaction', models.IntegerField(verbose_name='Interaction')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['popularity', 'interaction'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('approval_percentage', models.FloatField(verbose_name='Approval Percentage')),
                ('disapproval_percentage', models.FloatField(verbose_name='Disapproval Percentage')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
                'ordering': ['date'],
            },
        ),
    ]
