# Generated by Django 3.2.3 on 2021-08-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='no_data',
            field=models.BooleanField(default=True, verbose_name='No data found'),
        ),
    ]
