# Generated by Django 3.2.3 on 2021-08-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_no_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='interaction',
            field=models.IntegerField(default=0, verbose_name='Interaction'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='popularity',
            field=models.IntegerField(default=0, verbose_name='Popularity'),
        ),
    ]
