# Generated by Django 3.2.3 on 2021-08-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20210825_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication Date'),
        ),
    ]
