# Generated by Django 3.2.3 on 2021-08-26 22:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_auto_20210826_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('interaction', models.IntegerField(default=0, verbose_name='Interaction')),
                ('approval_percentage', models.FloatField(verbose_name='Approval Percentage')),
                ('disapproval_percentage', models.FloatField(verbose_name='Disapproval Percentage')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timelines',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-popularity'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='interaction',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AddField(
            model_name='timeline',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Subject'),
        ),
    ]
