# Generated by Django 3.2.3 on 2021-09-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_auto_20210826_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='approval_percentage',
            field=models.FloatField(default=0, verbose_name='Approval Percentage'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='disapproval_percentage',
            field=models.FloatField(default=0, verbose_name='Disapproval Percentage'),
        ),
    ]
