# Generated by Django 3.2.3 on 2021-09-12 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_data', models.IntegerField(verbose_name='Amount Data')),
                ('amount_positive', models.IntegerField(verbose_name='Positive Data')),
                ('amount_negative', models.IntegerField(verbose_name='Negative Data')),
                ('epochs', models.IntegerField(verbose_name='Epochs')),
                ('accuracy', models.FloatField(verbose_name='Accuracy')),
                ('correct_classify_percentage', models.FloatField(verbose_name='Correct classify percentage')),
                ('training_date', models.DateTimeField(verbose_name='Training Date')),
                ('training_version', models.CharField(max_length=80, verbose_name='Training version')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'ordering': ['-training_date'],
            },
        ),
    ]
